# Training configuration
GPU: [0]

VERBOSE: False

MODEL:
  MODE: 'PTMSNet_LOLv2_real'

# Optimization arguments.
OPTIM:
  BATCH: 8
  EPOCHS: 2000
  # EPOCH_DECAY: [10]
  LR_INITIAL: 1e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: False
  TRAIN_PS: 128
  VAL_PS: 128
  cutoff_freq: 15
  TRAIN_DIR: './datasets/LOLv2/real/train'       # path to training data
  VAL_DIR: './datasets/LOLv2/real/val' # path to validation data
  SAVE_DIR: './checkpoints/LOLv2_real'           # path to save models and images
